//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Returns.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PurchaseReturnsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchaseReturnsResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Returns.Resources.PurchaseReturnsResource", typeof(PurchaseReturnsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   入荷予定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArriveDate {
            get {
                return ResourceManager.GetString("ArriveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入返品確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_CREATE {
            get {
                return ResourceManager.GetString("BTN_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下代 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BuyingPrice {
            get {
                return ResourceManager.GetString("BuyingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryName1 {
            get {
                return ResourceManager.GetString("CategoryName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター住所 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterAddress {
            get {
                return ResourceManager.GetString("CenterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterName {
            get {
                return ResourceManager.GetString("CenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterS {
            get {
                return ResourceManager.GetString("CenterS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター電話番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterTel {
            get {
                return ResourceManager.GetString("CenterTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター郵便番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterZip {
            get {
                return ResourceManager.GetString("CenterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷確定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmDate {
            get {
                return ResourceManager.GetString("ConfirmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmQty {
            get {
                return ResourceManager.GetString("ConfirmQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入先返品確定を行います。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateMsg {
            get {
                return ResourceManager.GetString("CreateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸中のロケーションが存在します({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrInv {
            get {
                return ResourceManager.GetString("ErrInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceNoSearch {
            get {
                return ResourceManager.GetString("InvoiceNoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番・品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColor {
            get {
                return ResourceManager.GetString("ItemColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorS {
            get {
                return ResourceManager.GetString("ItemColorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemIdS {
            get {
                return ResourceManager.GetString("ItemIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番・品名： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemS {
            get {
                return ResourceManager.GetString("ItemS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSize {
            get {
                return ResourceManager.GetString("ItemSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeS {
            get {
                return ResourceManager.GetString("ItemSizeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuIdS {
            get {
                return ResourceManager.GetString("ItemSkuIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JanS {
            get {
                return ResourceManager.GetString("JanS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複数の納品書番号は同時に指定できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MultiInvoiceMsg {
            get {
                return ResourceManager.GetString("MultiInvoiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マスタ下代 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NormalBuyingPrice {
            get {
                return ResourceManager.GetString("NormalBuyingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下代0円が存在します。続行してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PriceMsg {
            get {
                return ResourceManager.GetString("PriceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発行日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintDate {
            get {
                return ResourceManager.GetString("PrintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発行者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintUser {
            get {
                return ResourceManager.GetString("PrintUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番、JAN、SKUのいずれかを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequiredEitherJan {
            get {
                return ResourceManager.GetString("RequiredEitherJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※返品数はデフォルトで 仕入れ先返品ロケ在庫数 と 返品可能数 の少ないほうを表示しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RetuenQtyComment {
            get {
                return ResourceManager.GetString("RetuenQtyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品数が返品可能数を超えています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnableOverMsg {
            get {
                return ResourceManager.GetString("ReturnableOverMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品可能数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnableQty {
            get {
                return ResourceManager.GetString("ReturnableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品伝票ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnId {
            get {
                return ResourceManager.GetString("ReturnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnQty {
            get {
                return ResourceManager.GetString("ReturnQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnQtySumS {
            get {
                return ResourceManager.GetString("ReturnQtySumS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sku {
            get {
                return ResourceManager.GetString("Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫数以下で入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockOverMsg {
            get {
                return ResourceManager.GetString("StockOverMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入返品ロケ在庫数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockQty {
            get {
                return ResourceManager.GetString("StockQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入返品ロケ在庫数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockQtySumS {
            get {
                return ResourceManager.GetString("StockQtySumS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入先： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorS {
            get {
                return ResourceManager.GetString("VendorS", resourceCulture);
            }
        }
    }
}
