//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Returns.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PurchaseCorrectionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchaseCorrectionResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Returns.Resources.PurchaseCorrectionResource", typeof(PurchaseCorrectionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引当数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocQty {
            get {
                return ResourceManager.GetString("AllocQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷予定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArriveDate {
            get {
                return ResourceManager.GetString("ArriveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷予定日： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArriveDateS {
            get {
                return ResourceManager.GetString("ArriveDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バラの在庫はありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BARA_NOT_ERR {
            get {
                return ResourceManager.GetString("BARA_NOT_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNo {
            get {
                return ResourceManager.GetString("BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNoS {
            get {
                return ResourceManager.GetString("BoxNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入訂正確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_CREATE {
            get {
                return ResourceManager.GetString("BTN_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下代 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BuyingPrice {
            get {
                return ResourceManager.GetString("BuyingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当のロケーションにはケースNoを持つ在庫情報はありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CASE_NOT_ERR {
            get {
                return ResourceManager.GetString("CASE_NOT_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNoを指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CASE_NULL_ERR {
            get {
                return ResourceManager.GetString("CASE_NULL_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケース出荷引当数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseAllocQty {
            get {
                return ResourceManager.GetString("CaseAllocQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseModalTitle {
            get {
                return ResourceManager.GetString("CaseModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryName1 {
            get {
                return ResourceManager.GetString("CategoryName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター住所 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterAddress {
            get {
                return ResourceManager.GetString("CenterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterName {
            get {
                return ResourceManager.GetString("CenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterS {
            get {
                return ResourceManager.GetString("CenterS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター電話番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterTel {
            get {
                return ResourceManager.GetString("CenterTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター郵便番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterZip {
            get {
                return ResourceManager.GetString("CenterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷確定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmDate {
            get {
                return ResourceManager.GetString("ConfirmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷確定日： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmDateS {
            get {
                return ResourceManager.GetString("ConfirmDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   訂正日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CorrectionDate {
            get {
                return ResourceManager.GetString("CorrectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入訂正確定を行います。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateMsg {
            get {
                return ResourceManager.GetString("CreateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力された差異数が実際の在庫数より多いです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_ADD {
            get {
                return ResourceManager.GetString("ERR_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ削除処理に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_DEL {
            get {
                return ResourceManager.GetString("ERR_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当JANの仕入入荷　納品書番号は登録可能な入荷確定日範囲内には存在しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_INVOICE_JAN {
            get {
                return ResourceManager.GetString("ERR_INVOICE_JAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ検索処理に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_SEARCH {
            get {
                return ResourceManager.GetString("ERR_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸中のロケーションが存在します({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrInv {
            get {
                return ResourceManager.GetString("ErrInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   差異数は0以外を入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrSaiQty {
            get {
                return ResourceManager.GetString("ErrSaiQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GradeId {
            get {
                return ResourceManager.GetString("GradeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格付： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GradeIdS {
            get {
                return ResourceManager.GetString("GradeIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号が違うか、登録可能入荷確定日が範囲外です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INVOICE_NO_NOT_ERR {
            get {
                return ResourceManager.GetString("INVOICE_NO_NOT_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号を指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INVOICE_NO_NULL_ERR {
            get {
                return ResourceManager.GetString("INVOICE_NO_NULL_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号/バッチNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceBatch {
            get {
                return ResourceManager.GetString("InvoiceBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceModalTitle {
            get {
                return ResourceManager.GetString("InvoiceModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceNoS {
            get {
                return ResourceManager.GetString("InvoiceNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番・品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColor {
            get {
                return ResourceManager.GetString("ItemColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorS {
            get {
                return ResourceManager.GetString("ItemColorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemIdS {
            get {
                return ResourceManager.GetString("ItemIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番・品名： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemS {
            get {
                return ResourceManager.GetString("ItemS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSize {
            get {
                return ResourceManager.GetString("ItemSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeS {
            get {
                return ResourceManager.GetString("ItemSizeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuIdS {
            get {
                return ResourceManager.GetString("ItemSkuIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当JANは存在しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JAN_NOT_ERR {
            get {
                return ResourceManager.GetString("JAN_NOT_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JANを指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JAN_NULL_ERR {
            get {
                return ResourceManager.GetString("JAN_NULL_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JANコード検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JanModalTitle {
            get {
                return ResourceManager.GetString("JanModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JanS {
            get {
                return ResourceManager.GetString("JanS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷可能数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KanouQty {
            get {
                return ResourceManager.GetString("KanouQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationCd {
            get {
                return ResourceManager.GetString("LocationCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationCdS {
            get {
                return ResourceManager.GetString("LocationCdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationClass {
            get {
                return ResourceManager.GetString("LocationClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション区分： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationClassS {
            get {
                return ResourceManager.GetString("LocationClassS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationModalTitle {
            get {
                return ResourceManager.GetString("LocationModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マスタ下代 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NormalBuyingPrice {
            get {
                return ResourceManager.GetString("NormalBuyingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下代0円が存在します。続行してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PriceMsg {
            get {
                return ResourceManager.GetString("PriceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発行日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintDate {
            get {
                return ResourceManager.GetString("PrintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発行者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintUser {
            get {
                return ResourceManager.GetString("PrintUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品伝票ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnId {
            get {
                return ResourceManager.GetString("ReturnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnQty {
            get {
                return ResourceManager.GetString("ReturnQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnQtySumS {
            get {
                return ResourceManager.GetString("ReturnQtySumS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   差異数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaiQty {
            get {
                return ResourceManager.GetString("SaiQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   差異数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaiQtyS {
            get {
                return ResourceManager.GetString("SaiQtyS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上代 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SellingPrice {
            get {
                return ResourceManager.GetString("SellingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sku {
            get {
                return ResourceManager.GetString("Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SkuS {
            get {
                return ResourceManager.GetString("SkuS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでにTC出荷引当済です。加算できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SortStatusAllocComErr {
            get {
                return ResourceManager.GetString("SortStatusAllocComErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TC出荷引当準備中です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SortStatusAllocErr {
            get {
                return ResourceManager.GetString("SortStatusAllocErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TC出荷引当済です。減算してよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SortStatusMsg {
            get {
                return ResourceManager.GetString("SortStatusMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫が存在しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STOCK_NOT_ERR {
            get {
                return ResourceManager.GetString("STOCK_NOT_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーションを指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STOCK_NULL_ERR {
            get {
                return ResourceManager.GetString("STOCK_NULL_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockQty {
            get {
                return ResourceManager.GetString("StockQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入返品ロケ在庫数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockQtySumS {
            get {
                return ResourceManager.GetString("StockQtySumS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入訂正処理が完了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SUC_TEISEI {
            get {
                return ResourceManager.GetString("SUC_TEISEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入先ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorId {
            get {
                return ResourceManager.GetString("VendorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入先： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorS {
            get {
                return ResourceManager.GetString("VendorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W下代 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WBuyingPrice {
            get {
                return ResourceManager.GetString("WBuyingPrice", resourceCulture);
            }
        }
    }
}
