//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Arrival.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArriveResultResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArriveResultResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Arrival.Resources.ArriveResultResource", typeof(ArriveResultResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   入荷状況 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArrivalStatus {
            get {
                return ResourceManager.GetString("ArrivalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArriveDate {
            get {
                return ResourceManager.GetString("ArriveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   倉庫ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績確定日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmDate {
            get {
                return ResourceManager.GetString("ConfirmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績確定担当者ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmUserId {
            get {
                return ResourceManager.GetString("ConfirmUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連携日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfRunDate {
            get {
                return ResourceManager.GetString("IfRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連携実行ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfRunId {
            get {
                return ResourceManager.GetString("IfRunId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連携状況 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfState {
            get {
                return ResourceManager.GetString("IfState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書行番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceSeq {
            get {
                return ResourceManager.GetString("InvoiceSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorId {
            get {
                return ResourceManager.GetString("ItemColorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品ID(品番) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeId {
            get {
                return ResourceManager.GetString("ItemSizeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuId {
            get {
                return ResourceManager.GetString("ItemSkuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultQty {
            get {
                return ResourceManager.GetString("ResultQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連携処理中フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendingFlag {
            get {
                return ResourceManager.GetString("SendingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入先ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorId {
            get {
                return ResourceManager.GetString("VendorId", resourceCulture);
            }
        }
    }
}
