//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Arrival.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArrInputPurchase01Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrInputPurchase01Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Arrival.Resources.ArrInputPurchase01Resource", typeof(ArrInputPurchase01Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   状況 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArrivalStatus {
            get {
                return ResourceManager.GetString("ArrivalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状況名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArrivalStatusName {
            get {
                return ResourceManager.GetString("ArrivalStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷予定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArrivePlanDate {
            get {
                return ResourceManager.GetString("ArrivePlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArrivePlanQty {
            get {
                return ResourceManager.GetString("ArrivePlanQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryName1 {
            get {
                return ResourceManager.GetString("CategoryName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センターコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuQty {
            get {
                return ResourceManager.GetString("ItemSkuQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineNo {
            get {
                return ResourceManager.GetString("LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケース予定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PackingPlanQty {
            get {
                return ResourceManager.GetString("PackingPlanQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケース実績数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PackingResultQty {
            get {
                return ResourceManager.GetString("PackingResultQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発注番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PoId {
            get {
                return ResourceManager.GetString("PoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultQty {
            get {
                return ResourceManager.GetString("ResultQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seq {
            get {
                return ResourceManager.GetString("Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入先ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorId {
            get {
                return ResourceManager.GetString("VendorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕入先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorName {
            get {
                return ResourceManager.GetString("VendorName", resourceCulture);
            }
        }
    }
}
