//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Arrival.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrintCaseLabelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintCaseLabelResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Arrival.Resources.PrintCaseLabelResource", typeof(PrintCaseLabelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   再発行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AgainRelease {
            get {
                return ResourceManager.GetString("AgainRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しいケースNoを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BOX_NO_ERROR {
            get {
                return ResourceManager.GetString("BOX_NO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再発行フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DispIssueFlag {
            get {
                return ResourceManager.GetString("DispIssueFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemCd {
            get {
                return ResourceManager.GetString("ItemCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JANコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベル番号バーコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelNumberBarcode {
            get {
                return ResourceManager.GetString("LabelNumberBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   枚数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumberofSheets {
            get {
                return ResourceManager.GetString("NumberofSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   枚数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumberofSheetsS {
            get {
                return ResourceManager.GetString("NumberofSheetsS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintDate {
            get {
                return ResourceManager.GetString("PrintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再発行ケースNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReleaseBoxNo {
            get {
                return ResourceManager.GetString("ReleaseBoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再発行ケースNo： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReleaseBoxNoS {
            get {
                return ResourceManager.GetString("ReleaseBoxNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発行区分： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReleaseClassS {
            get {
                return ResourceManager.GetString("ReleaseClassS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発行する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RELEASES {
            get {
                return ResourceManager.GetString("RELEASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
    }
}
