//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Stock.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdjustResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdjustResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Stock.Resources.AdjustResource", typeof(AdjustResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   調整ロケは指定できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdjustLocationError {
            get {
                return ResourceManager.GetString("AdjustLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   訂正後数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdjustQtyTo {
            get {
                return ResourceManager.GetString("AdjustQtyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫訂正数合計： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdjustQtyToSum {
            get {
                return ResourceManager.GetString("AdjustQtyToSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   訂正理由 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdjustReasonCd {
            get {
                return ResourceManager.GetString("AdjustReasonCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   訂正理由： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdjustReasonCdS {
            get {
                return ResourceManager.GetString("AdjustReasonCdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引当数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocQty {
            get {
                return ResourceManager.GetString("AllocQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引当数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocQtyS {
            get {
                return ResourceManager.GetString("AllocQtyS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引当数合計： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocQtySum {
            get {
                return ResourceManager.GetString("AllocQtySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫数（変更前）： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BeforeStockQtyS {
            get {
                return ResourceManager.GetString("BeforeStockQtyS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNo {
            get {
                return ResourceManager.GetString("BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNoS {
            get {
                return ResourceManager.GetString("BoxNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブランド： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrandIdS {
            get {
                return ResourceManager.GetString("BrandIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調整入力画面へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnAdjustInput {
            get {
                return ResourceManager.GetString("BtnAdjustInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnNew {
            get {
                return ResourceManager.GetString("BtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷姿 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseClass {
            get {
                return ResourceManager.GetString("CaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケース数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseQty {
            get {
                return ResourceManager.GetString("CaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryId1 {
            get {
                return ResourceManager.GetString("CategoryId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryIdS {
            get {
                return ResourceManager.GetString("CategoryIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センターコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterIdS {
            get {
                return ResourceManager.GetString("CenterIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterName {
            get {
                return ResourceManager.GetString("CenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に別のロケーションに登録済みです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DifferentLocationCd {
            get {
                return ResourceManager.GetString("DifferentLocationCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業部： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivisionIdS {
            get {
                return ResourceManager.GetString("DivisionIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   訂正後在庫数が引当数より少なくなっています！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrSmallerAdjustQtyTo {
            get {
                return ResourceManager.GetString("ErrSmallerAdjustQtyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GradeId {
            get {
                return ResourceManager.GetString("GradeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格付： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GrageIdS {
            get {
                return ResourceManager.GetString("GrageIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書No/バッチNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceNoForCreate {
            get {
                return ResourceManager.GetString("InvoiceNoForCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテム： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemCodeS {
            get {
                return ResourceManager.GetString("ItemCodeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColor {
            get {
                return ResourceManager.GetString("ItemColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラーID： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorIdS {
            get {
                return ResourceManager.GetString("ItemColorIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー名： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorNameS {
            get {
                return ResourceManager.GetString("ItemColorNameS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorS {
            get {
                return ResourceManager.GetString("ItemColorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番・品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemIdName {
            get {
                return ResourceManager.GetString("ItemIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemIdS {
            get {
                return ResourceManager.GetString("ItemIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemNameS {
            get {
                return ResourceManager.GetString("ItemNameS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSize {
            get {
                return ResourceManager.GetString("ItemSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズID： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeIdS {
            get {
                return ResourceManager.GetString("ItemSizeIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ名： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeNameS {
            get {
                return ResourceManager.GetString("ItemSizeNameS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeS {
            get {
                return ResourceManager.GetString("ItemSizeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuId {
            get {
                return ResourceManager.GetString("ItemSkuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuIdS {
            get {
                return ResourceManager.GetString("ItemSkuIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuSum {
            get {
                return ResourceManager.GetString("ItemSkuSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JanS {
            get {
                return ResourceManager.GetString("JanS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationCd {
            get {
                return ResourceManager.GetString("LocationCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationCdS {
            get {
                return ResourceManager.GetString("LocationCdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション区分： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationClassS {
            get {
                return ResourceManager.GetString("LocationClassS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション→SKU→格付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationSkuGrade {
            get {
                return ResourceManager.GetString("LocationSkuGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationSum {
            get {
                return ResourceManager.GetString("LocationSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エリア： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Locsec1S {
            get {
                return ResourceManager.GetString("Locsec1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   代表仕入先： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainVendorIdS {
            get {
                return ResourceManager.GetString("MainVendorIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※在庫調査Noは、移動入荷実績入力の調整の場合のみ登録してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSlipNo {
            get {
                return ResourceManager.GetString("MsgSlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoteS {
            get {
                return ResourceManager.GetString("NoteS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マスタに登録されていないロケーションです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotExistsLocation {
            get {
                return ResourceManager.GetString("NotExistsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNoは必須です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequiredBoxNo {
            get {
                return ResourceManager.GetString("RequiredBoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JANとSKUのどちらかは必須です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequiredWhichJan {
            get {
                return ResourceManager.GetString("RequiredWhichJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU→格付→ロケーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SkuGradeLocation {
            get {
                return ResourceManager.GetString("SkuGradeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫調査No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipNo {
            get {
                return ResourceManager.GetString("SlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫調査No： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipNoS {
            get {
                return ResourceManager.GetString("SlipNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockQty {
            get {
                return ResourceManager.GetString("StockQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫数合計： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockQtySum {
            get {
                return ResourceManager.GetString("StockQtySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未引当数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnAllocQty {
            get {
                return ResourceManager.GetString("UnAllocQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未引当数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnAllocQtyS {
            get {
                return ResourceManager.GetString("UnAllocQtyS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未引当数合計： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnAllocQtySum {
            get {
                return ResourceManager.GetString("UnAllocQtySum", resourceCulture);
            }
        }
    }
}
