//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Stock.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReferenceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReferenceResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Stock.Resources.ReferenceResource", typeof(ReferenceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   引当数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocQty {
            get {
                return ResourceManager.GetString("AllocQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引当数合計： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocQtySum {
            get {
                return ResourceManager.GetString("AllocQtySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケース明細へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BaseName {
            get {
                return ResourceManager.GetString("BaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNo {
            get {
                return ResourceManager.GetString("BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNoS {
            get {
                return ResourceManager.GetString("BoxNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo→SKU→格付→ロケーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxSku {
            get {
                return ResourceManager.GetString("BoxSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブランド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブランド： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrandIdS {
            get {
                return ResourceManager.GetString("BrandIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケース明細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnPackageStock {
            get {
                return ResourceManager.GetString("BtnPackageStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫照会リスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnPrint {
            get {
                return ResourceManager.GetString("BtnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫照会リスト(JAN) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnPrintJan {
            get {
                return ResourceManager.GetString("BtnPrintJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫明細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnStock {
            get {
                return ResourceManager.GetString("BtnStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケース数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseQty {
            get {
                return ResourceManager.GetString("CaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリ1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryId1 {
            get {
                return ResourceManager.GetString("CategoryId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryIdS {
            get {
                return ResourceManager.GetString("CategoryIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリ１名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryName1 {
            get {
                return ResourceManager.GetString("CategoryName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリ２名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryName2 {
            get {
                return ResourceManager.GetString("CategoryName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリ３名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryName3 {
            get {
                return ResourceManager.GetString("CategoryName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリ４名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryName4 {
            get {
                return ResourceManager.GetString("CategoryName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所在ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterIdS {
            get {
                return ResourceManager.GetString("CenterIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterName {
            get {
                return ResourceManager.GetString("CenterName", resourceCulture);
            }
        }

        /// <summary>
        ///   JAN入り明細フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DetailJanFlag
        {
            get
            {
                return ResourceManager.GetString("DetailJanFlag", resourceCulture);
            }
        }

        /// <summary>
        ///   事業部 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivisionId {
            get {
                return ResourceManager.GetString("DivisionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業部： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivisionIdS {
            get {
                return ResourceManager.GetString("DivisionIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GradeId {
            get {
                return ResourceManager.GetString("GradeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GradeName {
            get {
                return ResourceManager.GetString("GradeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格付： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GrageIdS {
            get {
                return ResourceManager.GetString("GrageIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行選択フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsCheck {
            get {
                return ResourceManager.GetString("IsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテム： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemCodeS {
            get {
                return ResourceManager.GetString("ItemCodeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColor {
            get {
                return ResourceManager.GetString("ItemColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorId {
            get {
                return ResourceManager.GetString("ItemColorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorIdS {
            get {
                return ResourceManager.GetString("ItemColorIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorName {
            get {
                return ResourceManager.GetString("ItemColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番・品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemIdName {
            get {
                return ResourceManager.GetString("ItemIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemIdS {
            get {
                return ResourceManager.GetString("ItemIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ｼｰｽﾞﾝ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSeasonName {
            get {
                return ResourceManager.GetString("ItemSeasonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSize {
            get {
                return ResourceManager.GetString("ItemSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeId {
            get {
                return ResourceManager.GetString("ItemSizeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeIdS {
            get {
                return ResourceManager.GetString("ItemSizeIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeName {
            get {
                return ResourceManager.GetString("ItemSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU→格付→ロケーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSku {
            get {
                return ResourceManager.GetString("ItemSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuId {
            get {
                return ResourceManager.GetString("ItemSkuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuIdS {
            get {
                return ResourceManager.GetString("ItemSkuIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuSum {
            get {
                return ResourceManager.GetString("ItemSkuSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JanS {
            get {
                return ResourceManager.GetString("JanS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション→SKU→格付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション→ケースNo→SKU→格付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationBox {
            get {
                return ResourceManager.GetString("LocationBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationCd {
            get {
                return ResourceManager.GetString("LocationCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationCdS {
            get {
                return ResourceManager.GetString("LocationCdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション区分： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationClassS {
            get {
                return ResourceManager.GetString("LocationClassS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション→SKU→格付→ケースNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationSku {
            get {
                return ResourceManager.GetString("LocationSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationSum {
            get {
                return ResourceManager.GetString("LocationSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Locsec_1 {
            get {
                return ResourceManager.GetString("Locsec_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Locsec1 {
            get {
                return ResourceManager.GetString("Locsec1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エリア： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Locsec1S {
            get {
                return ResourceManager.GetString("Locsec1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Locsec2 {
            get {
                return ResourceManager.GetString("Locsec2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Locsec3 {
            get {
                return ResourceManager.GetString("Locsec3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   段 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Locsec4 {
            get {
                return ResourceManager.GetString("Locsec4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   間口 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Locsec5 {
            get {
                return ResourceManager.GetString("Locsec5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   代表仕入先： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainVendorIdS {
            get {
                return ResourceManager.GetString("MainVendorIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上代単価(税抜) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NormalSellingPriceExTax {
            get {
                return ResourceManager.GetString("NormalSellingPriceExTax", resourceCulture);
            }
        }

        /// <summary>
        ///   ケース明細フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PackageStockReportFlg
        {
            get
            {
                return ResourceManager.GetString("PackageStockReportFlg", resourceCulture);
            }
        }

        /// <summary>
        ///   金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発行者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintUser {
            get {
                return ResourceManager.GetString("PrintUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   年度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeasonYear {
            get {
                return ResourceManager.GetString("SeasonYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU→格付→ロケーション→ケースNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SkuGrade {
            get {
                return ResourceManager.GetString("SkuGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockQty {
            get {
                return ResourceManager.GetString("StockQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫数0を表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockQtyFlagC {
            get {
                return ResourceManager.GetString("StockQtyFlagC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockQtyFlagS {
            get {
                return ResourceManager.GetString("StockQtyFlagS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫数合計： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockQtySum {
            get {
                return ResourceManager.GetString("StockQtySum", resourceCulture);
            }
        }

        /// <summary>
        ///   在庫連番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockSeq
        {
            get
            {
                return ResourceManager.GetString("StockSeq", resourceCulture);
            }
        }

        /// <summary>
        ///   ケース保管、バラ保管で複数ロケーションに存在する商品のみ表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StorageStatusC {
            get {
                return ResourceManager.GetString("StorageStatusC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格納状態： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StorageStatusS {
            get {
                return ResourceManager.GetString("StorageStatusS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未引当数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnAllocQty {
            get {
                return ResourceManager.GetString("UnAllocQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未引当数合計： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnAllocQtySum {
            get {
                return ResourceManager.GetString("UnAllocQtySum", resourceCulture);
            }
        }
    }
}
