//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Stock.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StkMoveResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StkMoveResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Stock.Resources.StkMoveResource", typeof(StkMoveResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   引当数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocQty {
            get {
                return ResourceManager.GetString("AllocQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケース数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseQty {
            get {
                return ResourceManager.GetString("CaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GradeId {
            get {
                return ResourceManager.GetString("GradeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行選択フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsCheck {
            get {
                return ResourceManager.GetString("IsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineNo {
            get {
                return ResourceManager.GetString("LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーションコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationCd {
            get {
                return ResourceManager.GetString("LocationCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未引当数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotAllocQty {
            get {
                return ResourceManager.GetString("NotAllocQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seq {
            get {
                return ResourceManager.GetString("Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SkuQty {
            get {
                return ResourceManager.GetString("SkuQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockQty {
            get {
                return ResourceManager.GetString("StockQty", resourceCulture);
            }
        }
    }
}
