//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IfRunUnitResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IfRunUnitResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Resources.IfRunUnitResource", typeof(IfRunUnitResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   異常終了時中断フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorStopFlag {
            get {
                return ResourceManager.GetString("ErrorStopFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連携データID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfDataId {
            get {
                return ResourceManager.GetString("IfDataId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行順序 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfRunSeq {
            get {
                return ResourceManager.GetString("IfRunSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連携実行単位ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfRunUnitId {
            get {
                return ResourceManager.GetString("IfRunUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連携システムID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfSystemId {
            get {
                return ResourceManager.GetString("IfSystemId", resourceCulture);
            }
        }
    }
}
