//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   引当中です・・・ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ALLOC_DOING {
            get {
                return ResourceManager.GetString("ALLOC_DOING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しいケースNoを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BOX_NO_ERROR {
            get {
                return ResourceManager.GetString("BOX_NO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績がありません。再発行できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BOX_NO_NOT_EXIST_ERROR {
            get {
                return ResourceManager.GetString("BOX_NO_NOT_EXIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類1または品番は必須項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryItemRequird {
            get {
                return ResourceManager.GetString("CategoryItemRequird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウントが失効しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_ACCOUNT_EXPIRATION {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引当中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_ALLOC_DOING {
            get {
                return ResourceManager.GetString("ERR_ALLOC_DOING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引当されているアソートケースの商品です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_ASORTCASE_UPDATE {
            get {
                return ResourceManager.GetString("ERR_ASORTCASE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ不具合が発生しています。管理者に連絡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_DEFECT {
            get {
                return ResourceManager.GetString("ERR_DEFECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行No{0},行No{1}：一つの出荷先に同じ適用開始日は登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_DUPLICATE_ROW {
            get {
                return ResourceManager.GetString("ERR_DUPLICATE_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択したロケーション区分と格付の組み合わせが、ロケ区分別格付マスタに存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_GRADE_NOT_EXIST {
            get {
                return ResourceManager.GetString("ERR_GRADE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーション区分がロケマスタメンテ不可でマスタに登録されています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_LOC_CLASS_MENTE_DISABLE {
            get {
                return ResourceManager.GetString("ERR_LOC_CLASS_MENTE_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在有効なデータは削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_LOC_TRANSPORTER_DELETE {
            get {
                return ResourceManager.GetString("ERR_LOC_TRANSPORTER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   浪速仕分コードマスタに設定されていない店舗です。浪速運送に設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_LOC_TRANSPORTER_NANIWA {
            get {
                return ResourceManager.GetString("ERR_LOC_TRANSPORTER_NANIWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーションコードがロケマスタメンテ不可のロケーション区分でマスタに登録済みです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_LOCATION_CD_MENET_DISABLE {
            get {
                return ResourceManager.GetString("ERR_LOCATION_CD_MENET_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センターコード、担当者コード、またはパスワードが違います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_LOGIN_MENU {
            get {
                return ResourceManager.GetString("ERR_LOGIN_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しい都道府県を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_NOT_PREFS {
            get {
                return ResourceManager.GetString("ERR_NOT_PREFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績数は予定数以下にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_OVER_PLAN {
            get {
                return ResourceManager.GetString("ERR_OVER_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが違います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_PASSWORD {
            get {
                return ResourceManager.GetString("ERR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期パスワードです。パスワードの変更を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_PASSWORD_DEFAULT {
            get {
                return ResourceManager.GetString("ERR_PASSWORD_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードの有効期限が切れています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_PASSWORD_EXPIRED {
            get {
                return ResourceManager.GetString("ERR_PASSWORD_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードは8文字以上で入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_PASSWORD_MIN_LENTH {
            get {
                return ResourceManager.GetString("ERR_PASSWORD_MIN_LENTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   規定回数以上、パスワード入力に失敗したため、アカウントが停止されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_PASSWORD_MISTYPE {
            get {
                return ResourceManager.GetString("ERR_PASSWORD_MISTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力したパスワードは、パスワードポリシーを満たしていません。ポリシーを確認し、再度入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_PASSWORD_POLICY {
            get {
                return ResourceManager.GetString("ERR_PASSWORD_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過去3回に使用されたパスワードです。新しいパスワードを変更してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_PASSWORD_REPEAT {
            get {
                return ResourceManager.GetString("ERR_PASSWORD_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷処理に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_PRINT {
            get {
                return ResourceManager.GetString("ERR_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理可能件数（設定値:{0}件）を超過しています。条件の指定を行い再度実行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_PROC_NUM_LIMIT {
            get {
                return ResourceManager.GetString("ERR_PROC_NUM_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他の倉庫と重複した電話番号です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_SAME_TEL {
            get {
                return ResourceManager.GetString("ERR_SAME_TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーションコード：{0}が、在庫テーブルに登録されているので、変更できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_STOCK_EXIST {
            get {
                return ResourceManager.GetString("ERR_STOCK_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーションコードが在庫テーブルに登録されているため、ロケーション区分と格付は変更できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_STOCK_EXIST_UPLOAD {
            get {
                return ResourceManager.GetString("ERR_STOCK_EXIST_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「在庫調査更新処理」で異常終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_STOCK_RESEARCH_UPDATE {
            get {
                return ResourceManager.GetString("ERR_STOCK_RESEARCH_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「在庫更新処理」で異常終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_STOCK_UPDATE {
            get {
                return ResourceManager.GetString("ERR_STOCK_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーIDと同一のパスワードは指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_USERID_PASSWORD_SAME {
            get {
                return ResourceManager.GetString("ERR_USERID_PASSWORD_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   郵便番号はハイフンなしで入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_ZIP_HYPHEN {
            get {
                return ResourceManager.GetString("ERR_ZIP_HYPHEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsg {
            get {
                return ResourceManager.GetString("ErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_END {
            get {
                return ResourceManager.GetString("ERROR_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}がファイル内で重複しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorUploadUniqueConstraintViolated {
            get {
                return ResourceManager.GetString("ErrorUploadUniqueConstraintViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力された{0}が汎用コードマスタに存在しません。
        ///汎用コードマスタ画面から登録してください。
        ///（汎用分類コード：{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenCdNotExistsError {
            get {
                return ResourceManager.GetString("GenCdNotExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以上で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理が正常に終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NORMAL_END {
            get {
                return ResourceManager.GetString("NORMAL_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}文字以上にしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasswordMinByte {
            get {
                return ResourceManager.GetString("PasswordMinByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   含められる文字は半角英数字です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasswordPolicyAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordPolicyAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーIDと同一のパスワードは使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasswordPolicyUserId {
            get {
                return ResourceManager.GetString("PasswordPolicyUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}～{2}の間で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閾値区分は1または2で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThresholdClassError {
            get {
                return ResourceManager.GetString("ThresholdClassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   割合は0～100の間で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThresholdRateRange {
            get {
                return ResourceManager.GetString("ThresholdRateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップロードしたデータは、ログインしたセンターIDで登録されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadCenterId {
            get {
                return ResourceManager.GetString("UploadCenterId", resourceCulture);
            }
        }
    }
}
