//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Move.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MovTransInput02Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MovTransInput02Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Move.Resources.MovTransInput02Resource", typeof(MovTransInput02Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   入荷予定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArrivePlanDate {
            get {
                return ResourceManager.GetString("ArrivePlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArrivePlanQty {
            get {
                return ResourceManager.GetString("ArrivePlanQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryId1 {
            get {
                return ResourceManager.GetString("CategoryId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類1名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryName1 {
            get {
                return ResourceManager.GetString("CategoryName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   倉庫ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績確定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmDate {
            get {
                return ResourceManager.GetString("ConfirmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputResultQty {
            get {
                return ResourceManager.GetString("InputResultQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorId {
            get {
                return ResourceManager.GetString("ItemColorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorName {
            get {
                return ResourceManager.GetString("ItemColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeId {
            get {
                return ResourceManager.GetString("ItemSizeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeName {
            get {
                return ResourceManager.GetString("ItemSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuId {
            get {
                return ResourceManager.GetString("ItemSkuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineNo {
            get {
                return ResourceManager.GetString("LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績数(更新前) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultQty {
            get {
                return ResourceManager.GetString("ResultQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seq {
            get {
                return ResourceManager.GetString("Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipNo {
            get {
                return ResourceManager.GetString("SlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipSeq {
            get {
                return ResourceManager.GetString("SlipSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransferClass {
            get {
                return ResourceManager.GetString("TransferClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動元店舗区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransferFromStoreClass {
            get {
                return ResourceManager.GetString("TransferFromStoreClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動元ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransferFromStoreId {
            get {
                return ResourceManager.GetString("TransferFromStoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動元名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransferFromStoreName {
            get {
                return ResourceManager.GetString("TransferFromStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷実績日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransferResultDate {
            get {
                return ResourceManager.GetString("TransferResultDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状況 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransferStatus {
            get {
                return ResourceManager.GetString("TransferStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状況名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransferStatusName {
            get {
                return ResourceManager.GetString("TransferStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動入荷実績.更新回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TtrUpdateCount {
            get {
                return ResourceManager.GetString("TtrUpdateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予定外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnplannedFlag {
            get {
                return ResourceManager.GetString("UnplannedFlag", resourceCulture);
            }
        }
    }
}
