//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormsResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Share.Common.Resources.FormsResource", typeof(FormsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   昇順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ASC {
            get {
                return ResourceManager.GetString("ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加画面へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_ADD {
            get {
                return ResourceManager.GetString("BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報を登録する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_BASE_CREATE {
            get {
                return ResourceManager.GetString("BTN_BASE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報を削除する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_BASE_DELETE {
            get {
                return ResourceManager.GetString("BTN_BASE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報を更新する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_BASE_UPDATE {
            get {
                return ResourceManager.GetString("BTN_BASE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_CANCEL {
            get {
                return ResourceManager.GetString("BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_CLEAR {
            get {
                return ResourceManager.GetString("BTN_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_CONFIRM {
            get {
                return ResourceManager.GetString("BTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績確定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_CONFIRM_ACTUAL {
            get {
                return ResourceManager.GetString("BTN_CONFIRM_ACTUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定解除する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("BTN_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_CREATE {
            get {
                return ResourceManager.GetString("BTN_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_DELETE {
            get {
                return ResourceManager.GetString("BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細画面へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_DETAIL {
            get {
                return ResourceManager.GetString("BTN_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_DOWNLOAD {
            get {
                return ResourceManager.GetString("BTN_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸取消 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_INVENTORY_CANCEL {
            get {
                return ResourceManager.GetString("BTN_INVENTORY_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_NEW {
            get {
                return ResourceManager.GetString("BTN_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_OK {
            get {
                return ResourceManager.GetString("BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷進捗照会明細へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_PURCHASEREFERENCE_DETAIL {
            get {
                return ResourceManager.GetString("BTN_PURCHASEREFERENCE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_REAL_CONFIRM {
            get {
                return ResourceManager.GetString("BTN_REAL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_RETURN {
            get {
                return ResourceManager.GetString("BTN_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_SAVE {
            get {
                return ResourceManager.GetString("BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_SEARCH {
            get {
                return ResourceManager.GetString("BTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件再表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_SEARCH_REDISPLAY {
            get {
                return ResourceManager.GetString("BTN_SEARCH_REDISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_SELECT {
            get {
                return ResourceManager.GetString("BTN_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_SELECT_ALL {
            get {
                return ResourceManager.GetString("BTN_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択解除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_SELECT_OFF {
            get {
                return ResourceManager.GetString("BTN_SELECT_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_SELECTING {
            get {
                return ResourceManager.GetString("BTN_SELECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仮確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_TEMPORARY_CONFIRM {
            get {
                return ResourceManager.GetString("BTN_TEMPORARY_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_UPDATE {
            get {
                return ResourceManager.GetString("BTN_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_UPLOAD {
            get {
                return ResourceManager.GetString("BTN_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   降順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DESC {
            get {
                return ResourceManager.GetString("DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示順： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DISPLAY_SHORT {
            get {
                return ResourceManager.GetString("DISPLAY_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルをアップロードします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileUplaodTitle {
            get {
                return ResourceManager.GetString("FileUplaodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルをここにドラッグ＆ドロップ、またはクリックでファイル選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileUploadMessage {
            get {
                return ResourceManager.GetString("FileUploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大ファイルサイズは{0}MBです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileUploadTitleMessage {
            get {
                return ResourceManager.GetString("FileUploadTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全{0}件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KENSU {
            get {
                return ResourceManager.GetString("KENSU", resourceCulture);
            }
        }
    }
}
