//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Share.Common.Resources.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}は半角英数字で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alphanumeric {
            get {
                return ResourceManager.GetString("Alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正な入力を検知したためサーバーとの接続を中断しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コードに数値以外の文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CodeNumberInValid {
            get {
                return ResourceManager.GetString("CodeNumberInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が{1}より小さくならないように入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DateGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("DateGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に登録されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_ALREADY_SAVED {
            get {
                return ResourceManager.GetString("ERR_ALREADY_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行No{0}：既に登録されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_ALREADY_SAVED_ROW {
            get {
                return ResourceManager.GetString("ERR_ALREADY_SAVED_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力されたパスワードは一致しません。新しいパスワードを両方のボックスに入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("ERR_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}&lt;{1}となるように入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_DATE_MINMAX {
            get {
                return ResourceManager.GetString("ERR_DATE_MINMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のユーザーに削除されたため削除できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_EXCLUSIVE_DELETE {
            get {
                return ResourceManager.GetString("ERR_EXCLUSIVE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のユーザーに登録されたため登録できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_EXCLUSIVE_INSERT {
            get {
                return ResourceManager.GetString("ERR_EXCLUSIVE_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のユーザーに変更されたため更新できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_EXCLUSIVE_UPDATE {
            get {
                return ResourceManager.GetString("ERR_EXCLUSIVE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のユーザーに変更されたためアップロードできませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_EXCLUSIVE_UPLOAD {
            get {
                return ResourceManager.GetString("ERR_EXCLUSIVE_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行No{0}：{1}は{2}桁以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_LENGTH {
            get {
                return ResourceManager.GetString("ERR_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事前定義されていないエラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_NO_DEFINITION {
            get {
                return ResourceManager.GetString("ERR_NO_DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行No{0}：{1}に数値以外の文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_NUMBER {
            get {
                return ResourceManager.GetString("ERR_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基幹システムで登録されたIDは削除できません(ID：{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_OEVER_DELETE {
            get {
                return ResourceManager.GetString("ERR_OEVER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}～{1}の間で入力してください。(整数:{2}桁、小数:{3}桁) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_OVER_DECIMAL {
            get {
                return ResourceManager.GetString("ERR_OVER_DECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}～{1}の間で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_OVER_INT {
            get {
                return ResourceManager.GetString("ERR_OVER_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過去3回に使用されたパスワードです。新しいパスワードを変更してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_PASSWORD_REPEAT {
            get {
                return ResourceManager.GetString("ERR_PASSWORD_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行No{0}：{1}は必須項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が未入力の行があります。{0}は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_REQUIRED_INPUT {
            get {
                return ResourceManager.GetString("ERR_REQUIRED_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーIDと同一のパスワードは指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERR_USERID_PASSWORD_SAME {
            get {
                return ResourceManager.GetString("ERR_USERID_PASSWORD_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が入力されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrNotInput {
            get {
                return ResourceManager.GetString("ErrNotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ErrorMessage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EventID {
            get {
                return ResourceManager.GetString("EventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角数字で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なアクセスが検知されたためサーバーとの接続を中断しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダッシュボードへ移動する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoToHome {
            get {
                return ResourceManager.GetString("GoToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角英数字記号で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムエラーを検知したためサーバーとの接続を中断しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引当処理中です　引当処理終了後に再度実行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IS_ALLOC_PROCESSING {
            get {
                return ResourceManager.GetString("IS_ALLOC_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日次処理中です　日次処理終了後に再度実行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IS_DAILY_PROCESSING {
            get {
                return ResourceManager.GetString("IS_DAILY_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸中です　棚卸処理終了後に再度実行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IS_TANA_LOC_PROCESSING {
            get {
                return ResourceManager.GetString("IS_TANA_LOC_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JANコードは12桁です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JanRegex12 {
            get {
                return ResourceManager.GetString("JanRegex12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cookieのサイズが{1}byteを超えています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeargeSizeCookie {
            get {
                return ResourceManager.GetString("LeargeSizeCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}桁で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LengthError {
            get {
                return ResourceManager.GetString("LengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の値がマスタに存在していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MasterNotExistsError {
            get {
                return ResourceManager.GetString("MasterNotExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以上で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}以上の値を入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MinValueMessage {
            get {
                return ResourceManager.GetString("MinValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のユーザーに変更されたため削除できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_ERR_EXCLUSIVE_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_EXCLUSIVE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当データが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が日付ではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDateError {
            get {
                return ResourceManager.GetString("NotDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご指定のページが見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は整数で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotIntError {
            get {
                return ResourceManager.GetString("NotIntError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}と{1}が一致しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotSameError {
            get {
                return ResourceManager.GetString("NotSameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角英数字で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OnlyAllowHalfSize {
            get {
                return ResourceManager.GetString("OnlyAllowHalfSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整数で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OnlyAllowInteger {
            get {
                return ResourceManager.GetString("OnlyAllowInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されている出荷指示データを引当します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_ALLOCATION {
            get {
                return ResourceManager.GetString("QUE_ALLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されているバッチNoを引当解除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_ALLOCATION_CANCEL {
            get {
                return ResourceManager.GetString("QUE_ALLOCATION_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績確定しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_CONFIRM_ACTUAL {
            get {
                return ResourceManager.GetString("QUE_CONFIRM_ACTUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定解除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("QUE_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_CREATE {
            get {
                return ResourceManager.GetString("QUE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動入荷検品作業中のデータがあります。登録処理を行いますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_CREATE_WORKING1 {
            get {
                return ResourceManager.GetString("QUE_CREATE_WORKING1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_DELETE {
            get {
                return ResourceManager.GetString("QUE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸取消しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_INVENTORY_CANCEL {
            get {
                return ResourceManager.GetString("QUE_INVENTORY_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本確定しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_INVENTORY_FORMAL_CONFIRM {
            get {
                return ResourceManager.GetString("QUE_INVENTORY_FORMAL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仮確定しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_INVENTORY_TEMPORARY_CONFIRM {
            get {
                return ResourceManager.GetString("QUE_INVENTORY_TEMPORARY_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されているロケーションの在庫を移動します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_LOCATION_MOVE {
            get {
                return ResourceManager.GetString("QUE_LOCATION_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_UPDATE {
            get {
                return ResourceManager.GetString("QUE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この{0}は過去に使用されていましたが現在は削除されています。同一の{0}で登録しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_UPDATE_OVERWRITE {
            get {
                return ResourceManager.GetString("QUE_UPDATE_OVERWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動入荷検品作業中のデータがあります。更新処理を行いますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUE_UPDATE_WORKING {
            get {
                return ResourceManager.GetString("QUE_UPDATE_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}～{2}の間で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ReplacementStrings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReplacementStrings {
            get {
                return ResourceManager.GetString("ReplacementStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   少なくとも1件選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECT_LESS_ONE_RECORD {
            get {
                return ResourceManager.GetString("SELECT_LESS_ONE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1件選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECT_ONE_RECORD {
            get {
                return ResourceManager.GetString("SELECT_ONE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SUC_DELETE {
            get {
                return ResourceManager.GetString("SUC_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SUC_INSERT {
            get {
                return ResourceManager.GetString("SUC_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SUC_UPDATE {
            get {
                return ResourceManager.GetString("SUC_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップロードしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SUC_UPLOAD {
            get {
                return ResourceManager.GetString("SUC_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じ問題が繰り返される場合はシステム管理者に連絡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextEscalation {
            get {
                return ResourceManager.GetString("TextEscalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面の処理中にこのページに遷移した場合はもう一度画面に戻って再度処理を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextReprocessing {
            get {
                return ResourceManager.GetString("TextReprocessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TimeWritten に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeWritten {
            get {
                return ResourceManager.GetString("TimeWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLE_CONFIRM {
            get {
                return ResourceManager.GetString("TITLE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLE_ERROR {
            get {
                return ResourceManager.GetString("TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLE_INFORMATION {
            get {
                return ResourceManager.GetString("TITLE_INFORMATION", resourceCulture);
            }
        }
    }
}
