//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Master.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BoxSettingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoxSettingResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Master.Resources.BoxSettingResource", typeof(BoxSettingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ケース閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BaseName {
            get {
                return ResourceManager.GetString("BaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxSettingsId {
            get {
                return ResourceManager.GetString("BoxSettingsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行追加する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnAddLine {
            get {
                return ResourceManager.GetString("BtnAddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryId1 {
            get {
                return ResourceManager.GetString("CategoryId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryId2 {
            get {
                return ResourceManager.GetString("CategoryId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryId3 {
            get {
                return ResourceManager.GetString("CategoryId3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryId4 {
            get {
                return ResourceManager.GetString("CategoryId4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所在ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterName {
            get {
                return ResourceManager.GetString("CenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番指定は品番のみで設定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DecimalValue {
            get {
                return ResourceManager.GetString("DecimalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteFlag {
            get {
                return ResourceManager.GetString("DeleteFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsg {
            get {
                return ResourceManager.GetString("ErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IntValue {
            get {
                return ResourceManager.GetString("IntValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷主ID＋所在ID＋分類1～4＋商品ID　の単位　で重複不可とする。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyRepeat {
            get {
                return ResourceManager.GetString("KeyRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行No{0}： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineNo {
            get {
                return ResourceManager.GetString("LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0以上100以下の値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RateValue {
            get {
                return ResourceManager.GetString("RateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閾値区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThresholdClass {
            get {
                return ResourceManager.GetString("ThresholdClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0、1、2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThresholdClassValue {
            get {
                return ResourceManager.GetString("ThresholdClassValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   率(%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThresholdRate {
            get {
                return ResourceManager.GetString("ThresholdRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThresholdSku {
            get {
                return ResourceManager.GetString("ThresholdSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケース閾値マスタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
