//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Master.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditLayoutResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditLayoutResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Master.Resources.EditLayoutResource", typeof(EditLayoutResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バイト数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ByteCount {
            get {
                return ResourceManager.GetString("ByteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所在ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Constraint {
            get {
                return ResourceManager.GetString("Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ内容 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataDetail {
            get {
                return ResourceManager.GetString("DataDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ型 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの削除を完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   桁数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DigitCount {
            get {
                return ResourceManager.GetString("DigitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditCondition {
            get {
                return ResourceManager.GetString("EditCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト設定(条件設定画面) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditLayout_EditCondition {
            get {
                return ResourceManager.GetString("EditLayout_EditCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト設定(取込設定画面) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditLayout_EditImport {
            get {
                return ResourceManager.GetString("EditLayout_EditImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト設定(出力設定画面) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditLayout_EditOutput {
            get {
                return ResourceManager.GetString("EditLayout_EditOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト設定(ソート設定画面) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditLayout_EditSort {
            get {
                return ResourceManager.GetString("EditLayout_EditSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト設定(レイアウト選択画面) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditLayout_Select {
            get {
                return ResourceManager.GetString("EditLayout_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditOutput {
            get {
                return ResourceManager.GetString("EditOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力ファイル設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditOutputFile {
            get {
                return ResourceManager.GetString("EditOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソート設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditSort {
            get {
                return ResourceManager.GetString("EditSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   囲み文字 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EncloseType {
            get {
                return ResourceManager.GetString("EncloseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EncodeType {
            get {
                return ResourceManager.GetString("EncodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたレイアウト名は存在しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExistsLayoutName {
            get {
                return ResourceManager.GetString("ExistsLayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   固定値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FixedValue {
            get {
                return ResourceManager.GetString("FixedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報取得 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetInfomation {
            get {
                return ResourceManager.GetString("GetInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   見出し行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HeadingRow {
            get {
                return ResourceManager.GetString("HeadingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportClass {
            get {
                return ResourceManager.GetString("ImportClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入出力区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IoClass {
            get {
                return ResourceManager.GetString("IoClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終更新者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LastUpdateUser {
            get {
                return ResourceManager.GetString("LastUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LayoutName {
            get {
                return ResourceManager.GetString("LayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeUser {
            get {
                return ResourceManager.GetString("MakeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最低1つは入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MustInputEditingOutputFile {
            get {
                return ResourceManager.GetString("MustInputEditingOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込ファイルに対象データが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotExistsImportData {
            get {
                return ResourceManager.GetString("NotExistsImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutputTitle {
            get {
                return ResourceManager.GetString("OutputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   埋め文字 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PadChar {
            get {
                return ResourceManager.GetString("PadChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   埋め方向 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PadDirection {
            get {
                return ResourceManager.GetString("PadDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前埋め に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PadLeft {
            get {
                return ResourceManager.GetString("PadLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   後埋め に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PadRight {
            get {
                return ResourceManager.GetString("PadRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一意キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrimaryKey {
            get {
                return ResourceManager.GetString("PrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソート方向 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SortDirection {
            get {
                return ResourceManager.GetString("SortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソート順位 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TableInfo {
            get {
                return ResourceManager.GetString("TableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TableToBeImorted {
            get {
                return ResourceManager.GetString("TableToBeImorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込先テーブル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetTable {
            get {
                return ResourceManager.GetString("TargetTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TestOutput {
            get {
                return ResourceManager.GetString("TestOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細画面へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToDetail {
            get {
                return ResourceManager.GetString("ToDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateClass {
            get {
                return ResourceManager.GetString("UpdateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadClass {
            get {
                return ResourceManager.GetString("UploadClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込ファイル情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadFileInfo {
            get {
                return ResourceManager.GetString("UploadFileInfo", resourceCulture);
            }
        }
    }
}
