//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Master.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutDetailResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutDetailResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Master.Resources.LayoutDetailResource", typeof(LayoutDetailResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   所在ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラムID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnId {
            get {
                return ResourceManager.GetString("ColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラム№ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnNo {
            get {
                return ResourceManager.GetString("ColumnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ型 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteFlag {
            get {
                return ResourceManager.GetString("DeleteFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   桁数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Digit {
            get {
                return ResourceManager.GetString("Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EndPosition {
            get {
                return ResourceManager.GetString("EndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   固定値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FixedValue {
            get {
                return ResourceManager.GetString("FixedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportClass {
            get {
                return ResourceManager.GetString("ImportClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行№ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineNo {
            get {
                return ResourceManager.GetString("LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成プログラム名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeProgramName {
            get {
                return ResourceManager.GetString("MakeProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeUserId {
            get {
                return ResourceManager.GetString("MakeUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オブジェクトID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ObjectId {
            get {
                return ResourceManager.GetString("ObjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   埋め文字 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PadChar {
            get {
                return ResourceManager.GetString("PadChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字埋め有無 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PadClass {
            get {
                return ResourceManager.GetString("PadClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字埋め方向 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PadDirection {
            get {
                return ResourceManager.GetString("PadDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipperId {
            get {
                return ResourceManager.GetString("ShipperId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartPosition {
            get {
                return ResourceManager.GetString("StartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブ№ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubNo {
            get {
                return ResourceManager.GetString("SubNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テンプレートID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TemplateId {
            get {
                return ResourceManager.GetString("TemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新有無 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateClass {
            get {
                return ResourceManager.GetString("UpdateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateCount {
            get {
                return ResourceManager.GetString("UpdateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新プログラム名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateProgramName {
            get {
                return ResourceManager.GetString("UpdateProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateUserId {
            get {
                return ResourceManager.GetString("UpdateUserId", resourceCulture);
            }
        }
    }
}
