//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Master.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocTransporterResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocTransporterResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Master.Resources.LocTransporterResource", typeof(LocTransporterResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   エリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター別店舗別配送業者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BaseName {
            get {
                return ResourceManager.GetString("BaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加画面へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_ADD {
            get {
                return ResourceManager.GetString("BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一括変更する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_ALL_UPDATE {
            get {
                return ResourceManager.GetString("BTN_ALL_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行クリアする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_CLEAR {
            get {
                return ResourceManager.GetString("BTN_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先を選択する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_SYUKKASAKI_SELECT {
            get {
                return ResourceManager.GetString("BTN_SYUKKASAKI_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細画面へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_UPD {
            get {
                return ResourceManager.GetString("BTN_UPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   倉庫ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お客様コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientCd {
            get {
                return ResourceManager.GetString("ClientCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   浪速顧客コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientCdNaniwa {
            get {
                return ResourceManager.GetString("ClientCdNaniwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   佐川顧客コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientCdSagawa {
            get {
                return ResourceManager.GetString("ClientCdSagawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WS顧客コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientCdWs {
            get {
                return ResourceManager.GetString("ClientCdWs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※追加した行のみ適用開始日の変更が可能です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WS顧客コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsignorId {
            get {
                return ResourceManager.GetString("ConsignorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   浪速顧客コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlId {
            get {
                return ResourceManager.GetString("ControlId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsg {
            get {
                return ResourceManager.GetString("ErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   祝 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hol {
            get {
                return ResourceManager.GetString("Hol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ﾘｰﾄﾞ
        ///ﾀｲﾑ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeadTime {
            get {
                return ResourceManager.GetString("LeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リードタイム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeadTimes {
            get {
                return ResourceManager.GetString("LeadTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リードタイム(金) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeadTimesFri {
            get {
                return ResourceManager.GetString("LeadTimesFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リードタイム(祝) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeadTimesHol {
            get {
                return ResourceManager.GetString("LeadTimesHol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リードタイム(月) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeadTimesMon {
            get {
                return ResourceManager.GetString("LeadTimesMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リードタイム(土) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeadTimesSat {
            get {
                return ResourceManager.GetString("LeadTimesSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リードタイム(日) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeadTimesSun {
            get {
                return ResourceManager.GetString("LeadTimesSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リードタイム(木) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeadTimesThu {
            get {
                return ResourceManager.GetString("LeadTimesThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リードタイム(火) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeadTimesTue {
            get {
                return ResourceManager.GetString("LeadTimesTue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リードタイム(水) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LeadTimesWed {
            get {
                return ResourceManager.GetString("LeadTimesWed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ﾒｲﾝ
        ///ﾘｰﾄﾞ
        ///ﾀｲﾑ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLeadTime {
            get {
                return ResourceManager.GetString("MainLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メイン
        ///配送業者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainTransporter {
            get {
                return ResourceManager.GetString("MainTransporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   土 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipFromCenter {
            get {
                return ResourceManager.GetString("ShipFromCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷元倉庫区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipFromCenterClass {
            get {
                return ResourceManager.GetString("ShipFromCenterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷元倉庫名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipFromCenterName {
            get {
                return ResourceManager.GetString("ShipFromCenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所在地 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipStore {
            get {
                return ResourceManager.GetString("ShipStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToClass {
            get {
                return ResourceManager.GetString("ShipToClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStore {
            get {
                return ResourceManager.GetString("ShipToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先店舗区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreClass {
            get {
                return ResourceManager.GetString("ShipToStoreClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先店舗ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreId {
            get {
                return ResourceManager.GetString("ShipToStoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先所在名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreName {
            get {
                return ResourceManager.GetString("ShipToStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷元→出荷先→適用開始日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SKey1 {
            get {
                return ResourceManager.GetString("SKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷元→適用開始日→出荷先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SKey2 {
            get {
                return ResourceManager.GetString("SKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適用開始日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在有効なデータのみ表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartDateNewTime {
            get {
                return ResourceManager.GetString("StartDateNewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適用開始日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TekiyouStartDate {
            get {
                return ResourceManager.GetString("TekiyouStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター別店舗別配送業者マスタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Transporter {
            get {
                return ResourceManager.GetString("Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterId {
            get {
                return ResourceManager.GetString("TransporterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者ID(金) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterIdFri {
            get {
                return ResourceManager.GetString("TransporterIdFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者ID(祝) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterIdHol {
            get {
                return ResourceManager.GetString("TransporterIdHol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者ID(月) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterIdMon {
            get {
                return ResourceManager.GetString("TransporterIdMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者ID(土) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterIdSat {
            get {
                return ResourceManager.GetString("TransporterIdSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者ID(日) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterIdSun {
            get {
                return ResourceManager.GetString("TransporterIdSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者ID(木) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterIdThu {
            get {
                return ResourceManager.GetString("TransporterIdThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者ID(火) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterIdTue {
            get {
                return ResourceManager.GetString("TransporterIdTue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者ID(水) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterIdWed {
            get {
                return ResourceManager.GetString("TransporterIdWed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
    }
}
