//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Master.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NaniwaSortingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NaniwaSortingResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Master.Resources.NaniwaSortingResource", typeof(NaniwaSortingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   浪速運送配送センター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenDivCdNaniwaDeliCenterCd {
            get {
                return ResourceManager.GetString("GenDivCdNaniwaDeliCenterCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送センターコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NaniwaDeliCenterCd {
            get {
                return ResourceManager.GetString("NaniwaDeliCenterCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送センターコード→店舗ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NaniwaDeliCenterCdStoreId {
            get {
                return ResourceManager.GetString("NaniwaDeliCenterCdStoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送センター名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NaniwaDeliCenterName {
            get {
                return ResourceManager.GetString("NaniwaDeliCenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreId {
            get {
                return ResourceManager.GetString("StoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
    }
}
