//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Master.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoreResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Master.Resources.StoreResource", typeof(StoreResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   エリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AreaId {
            get {
                return ResourceManager.GetString("AreaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エリアマネージャーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AreaManagerId {
            get {
                return ResourceManager.GetString("AreaManagerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BaseName {
            get {
                return ResourceManager.GetString("BaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所属事業所ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BelongsOfficeId {
            get {
                return ResourceManager.GetString("BelongsOfficeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブランド区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrandClass {
            get {
                return ResourceManager.GetString("BrandClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャネルID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelId {
            get {
                return ResourceManager.GetString("ChannelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャネル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelName {
            get {
                return ResourceManager.GetString("ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉店区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseClass {
            get {
                return ResourceManager.GetString("CloseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉店日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseDate {
            get {
                return ResourceManager.GetString("CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉店日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseDateSearch {
            get {
                return ResourceManager.GetString("CloseDateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyClass {
            get {
                return ResourceManager.GetString("CompanyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管轄倉庫コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlCenterId {
            get {
                return ResourceManager.GetString("ControlCenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteFlag {
            get {
                return ResourceManager.GetString("DeleteFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除フラグ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteFlagSearch {
            get {
                return ResourceManager.GetString("DeleteFlagSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除済みのデータを表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteFlagSearch2 {
            get {
                return ResourceManager.GetString("DeleteFlagSearch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業部 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業部ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivisionId {
            get {
                return ResourceManager.GetString("DivisionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ECサイト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EcClass {
            get {
                return ResourceManager.GetString("EcClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検品必須 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionMustFlag {
            get {
                return ResourceManager.GetString("InspectionMustFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検品必須： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionMustFlagSearch {
            get {
                return ResourceManager.GetString("InspectionMustFlagSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検品必須のみを表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionMustFlagSearch2 {
            get {
                return ResourceManager.GetString("InspectionMustFlagSearch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状用店舗名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceStoreName {
            get {
                return ResourceManager.GetString("InvoiceStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規追加日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeDate {
            get {
                return ResourceManager.GetString("MakeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ新規登録日： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeDateSearch {
            get {
                return ResourceManager.GetString("MakeDateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開店日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDate {
            get {
                return ResourceManager.GetString("OpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開店日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDateSearch {
            get {
                return ResourceManager.GetString("OpenDateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開店日→店舗コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDateStoreId {
            get {
                return ResourceManager.GetString("OpenDateStoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕分パターンID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PatternId {
            get {
                return ResourceManager.GetString("PatternId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   都道府県 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrefId {
            get {
                return ResourceManager.GetString("PrefId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金額丸目区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoundClass {
            get {
                return ResourceManager.GetString("RoundClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   売上基準区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaleBaseClass {
            get {
                return ResourceManager.GetString("SaleBaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   坪数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SiteareaQty {
            get {
                return ResourceManager.GetString("SiteareaQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   坪タイプID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SiteareaTypeId {
            get {
                return ResourceManager.GetString("SiteareaTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   欠品不可 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockOutDisableFlag {
            get {
                return ResourceManager.GetString("StockOutDisableFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   それ以降の住所1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreAddress1 {
            get {
                return ResourceManager.GetString("StoreAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   それ以降の住所2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreAddress2 {
            get {
                return ResourceManager.GetString("StoreAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   それ以降の住所3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreAddress3 {
            get {
                return ResourceManager.GetString("StoreAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   住所： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreAddressSearch {
            get {
                return ResourceManager.GetString("StoreAddressSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   市区町村（カナ） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreCityKanaName {
            get {
                return ResourceManager.GetString("StoreCityKanaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   市区町村 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreCityName {
            get {
                return ResourceManager.GetString("StoreCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreClass {
            get {
                return ResourceManager.GetString("StoreClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗区分： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreClassSearch {
            get {
                return ResourceManager.GetString("StoreClassSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所在国 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreCountry {
            get {
                return ResourceManager.GetString("StoreCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAX に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreFax {
            get {
                return ResourceManager.GetString("StoreFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreId {
            get {
                return ResourceManager.GetString("StoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗コード： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreIdSearch {
            get {
                return ResourceManager.GetString("StoreIdSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   それ以降の住所1（カナ） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreKanaAddress1 {
            get {
                return ResourceManager.GetString("StoreKanaAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   それ以降の住所2（カナ） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreKanaAddress2 {
            get {
                return ResourceManager.GetString("StoreKanaAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   それ以降の住所3（カナ） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreKanaAddress3 {
            get {
                return ResourceManager.GetString("StoreKanaAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗名（カナ） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreKanaName {
            get {
                return ResourceManager.GetString("StoreKanaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗名1（カナ） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreKanaName1 {
            get {
                return ResourceManager.GetString("StoreKanaName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗名2（カナ） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreKanaName2 {
            get {
                return ResourceManager.GetString("StoreKanaName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗名（略称カナ） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreKanaShortName {
            get {
                return ResourceManager.GetString("StoreKanaShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreMail1 {
            get {
                return ResourceManager.GetString("StoreMail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreMail2 {
            get {
                return ResourceManager.GetString("StoreMail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗名1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreName1 {
            get {
                return ResourceManager.GetString("StoreName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗名2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreName2 {
            get {
                return ResourceManager.GetString("StoreName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗名： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreNameSearch {
            get {
                return ResourceManager.GetString("StoreNameSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   都道府県（カナ） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StorePrefKanaName {
            get {
                return ResourceManager.GetString("StorePrefKanaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   都道府県 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StorePrefName {
            get {
                return ResourceManager.GetString("StorePrefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗ランク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreRankId {
            get {
                return ResourceManager.GetString("StoreRankId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗名（略称） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreShortName {
            get {
                return ResourceManager.GetString("StoreShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreTel {
            get {
                return ResourceManager.GetString("StoreTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEL： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreTelSearch {
            get {
                return ResourceManager.GetString("StoreTelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   郵便番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreZip {
            get {
                return ResourceManager.GetString("StoreZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仮店舗区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TempStoreClass {
            get {
                return ResourceManager.GetString("TempStoreClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterId {
            get {
                return ResourceManager.GetString("TransporterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
    }
}
