//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Ship.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BtoBReferenceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BtoBReferenceResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Ship.Resources.BtoBReferenceResource", typeof(BtoBReferenceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   予定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocQty {
            get {
                return ResourceManager.GetString("AllocQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全欠品 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllStock {
            get {
                return ResourceManager.GetString("AllStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バッチ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BatchName {
            get {
                return ResourceManager.GetString("BatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バッチNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BatchNo {
            get {
                return ResourceManager.GetString("BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バッチNo： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BatchNoS {
            get {
                return ResourceManager.GetString("BatchNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNo {
            get {
                return ResourceManager.GetString("BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNoS {
            get {
                return ResourceManager.GetString("BoxNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブランド： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrandS {
            get {
                return ResourceManager.GetString("BrandS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード(ケース) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_DOWNLOAD_CASE {
            get {
                return ResourceManager.GetString("BTN_DOWNLOAD_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード(明細) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_DOWNLOAD_MEISAI {
            get {
                return ResourceManager.GetString("BTN_DOWNLOAD_MEISAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   梱包明細へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnPackageDetail {
            get {
                return ResourceManager.GetString("BtnPackageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   梱包明細(JAN) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnPrintJan {
            get {
                return ResourceManager.GetString("BtnPrintJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnShipConfirm {
            get {
                return ResourceManager.GetString("BtnShipConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カートン確定済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseKaku {
            get {
                return ResourceManager.GetString("CaseKaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カートン確定日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseKakuDate {
            get {
                return ResourceManager.GetString("CaseKakuDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カートン確定日時： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseKakuDateS {
            get {
                return ResourceManager.GetString("CaseKakuDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カートン確定担当者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseKakuUser {
            get {
                return ResourceManager.GetString("CaseKakuUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カートン確定担当者： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseKakuUserS {
            get {
                return ResourceManager.GetString("CaseKakuUserS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category1 {
            get {
                return ResourceManager.GetString("Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryS {
            get {
                return ResourceManager.GetString("CategoryS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センターID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterS {
            get {
                return ResourceManager.GetString("CenterS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   佐川お客様コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientCd {
            get {
                return ResourceManager.GetString("ClientCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日次済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliNo {
            get {
                return ResourceManager.GetString("DeliNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   浪速送り状親No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliNo2 {
            get {
                return ResourceManager.GetString("DeliNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状No： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliNoS {
            get {
                return ResourceManager.GetString("DeliNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕分番号： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliShiwakeCdS {
            get {
                return ResourceManager.GetString("DeliShiwakeCdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   明細数合計： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DetailSum {
            get {
                return ResourceManager.GetString("DetailSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   梱包明細情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DetailTitle {
            get {
                return ResourceManager.GetString("DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業部： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivisionS {
            get {
                return ResourceManager.GetString("DivisionS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付なし、時間のみ指定は不可。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrNoDate {
            get {
                return ResourceManager.GetString("ErrNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時刻の書式が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrTime {
            get {
                return ResourceManager.GetString("ErrTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指示区分： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstructClassS {
            get {
                return ResourceManager.GetString("InstructClassS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状発行済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoicePrint {
            get {
                return ResourceManager.GetString("InvoicePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番・品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColor {
            get {
                return ResourceManager.GetString("ItemColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorName {
            get {
                return ResourceManager.GetString("ItemColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorNm {
            get {
                return ResourceManager.GetString("ItemColorNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemIdS {
            get {
                return ResourceManager.GetString("ItemIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemNm {
            get {
                return ResourceManager.GetString("ItemNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテム： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemS {
            get {
                return ResourceManager.GetString("ItemS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSize {
            get {
                return ResourceManager.GetString("ItemSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeName {
            get {
                return ResourceManager.GetString("ItemSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeNm {
            get {
                return ResourceManager.GetString("ItemSizeNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuId {
            get {
                return ResourceManager.GetString("ItemSkuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU数合計： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuSum {
            get {
                return ResourceManager.GetString("ItemSkuSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JanS {
            get {
                return ResourceManager.GetString("JanS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷確定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KakuDate {
            get {
                return ResourceManager.GetString("KakuDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷確定日： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KakuDateS {
            get {
                return ResourceManager.GetString("KakuDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定担当者： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KakuUserNameS {
            get {
                return ResourceManager.GetString("KakuUserNameS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検品日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KenDate {
            get {
                return ResourceManager.GetString("KenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検品日時： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KenDateS {
            get {
                return ResourceManager.GetString("KenDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検品担当者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KenUser {
            get {
                return ResourceManager.GetString("KenUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検品担当者： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KenUserS {
            get {
                return ResourceManager.GetString("KenUserS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   代表仕入先： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainVendorS {
            get {
                return ResourceManager.GetString("MainVendorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受信日時From に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeDateTimeFrom {
            get {
                return ResourceManager.GetString("MakeDateTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受信日時： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeDateTimeS {
            get {
                return ResourceManager.GetString("MakeDateTimeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受信日時To に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeDateTimeTo {
            get {
                return ResourceManager.GetString("MakeDateTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上代単価 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NormalSellingPriceExTax {
            get {
                return ResourceManager.GetString("NormalSellingPriceExTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NouhinNo {
            get {
                return ResourceManager.GetString("NouhinNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NouhinNoS {
            get {
                return ResourceManager.GetString("NouhinNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書発行日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NouhinPrnDate {
            get {
                return ResourceManager.GetString("NouhinPrnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書発行日時： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NouhinPrnDateS {
            get {
                return ResourceManager.GetString("NouhinPrnDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書発行担当者： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NouhinPrnUserS {
            get {
                return ResourceManager.GetString("NouhinPrnUserS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書発行担当者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NouhinUser {
            get {
                return ResourceManager.GetString("NouhinUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書発行者ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NouhinUserId {
            get {
                return ResourceManager.GetString("NouhinUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書発行者名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NouhinUserName {
            get {
                return ResourceManager.GetString("NouhinUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定日： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PackKakuDateS {
            get {
                return ResourceManager.GetString("PackKakuDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書発行済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書再発行待ち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RePrint {
            get {
                return ResourceManager.GetString("RePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultQty {
            get {
                return ResourceManager.GetString("ResultQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績数合計： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultQtySum {
            get {
                return ResourceManager.GetString("ResultQtySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過去分含む に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipBoxStatusOldS {
            get {
                return ResourceManager.GetString("ShipBoxStatusOldS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipBoxStatusS {
            get {
                return ResourceManager.GetString("ShipBoxStatusS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されている出荷指示データを出荷確定します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipConfirmMessage {
            get {
                return ResourceManager.GetString("ShipConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷指示ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipInstructId {
            get {
                return ResourceManager.GetString("ShipInstructId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷指示ID： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipInstructIdS {
            get {
                return ResourceManager.GetString("ShipInstructIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷指示ID→明細ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipInstructIdSeq {
            get {
                return ResourceManager.GetString("ShipInstructIdSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   明細ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipInstructSeq {
            get {
                return ResourceManager.GetString("ShipInstructSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷予定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipPlanDate {
            get {
                return ResourceManager.GetString("ShipPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷予定日： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipPlanDateS {
            get {
                return ResourceManager.GetString("ShipPlanDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipStatus {
            get {
                return ResourceManager.GetString("ShipStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipStop {
            get {
                return ResourceManager.GetString("ShipStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStore {
            get {
                return ResourceManager.GetString("ShipToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreId {
            get {
                return ResourceManager.GetString("ShipToStoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先ID→ケースNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreIdBoxNo {
            get {
                return ResourceManager.GetString("ShipToStoreIdBoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreName {
            get {
                return ResourceManager.GetString("ShipToStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreS {
            get {
                return ResourceManager.GetString("ShipToStoreS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SkuS {
            get {
                return ResourceManager.GetString("SkuS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU→出荷指示ID→明細ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SkuShipInstructIdSeq {
            get {
                return ResourceManager.GetString("SkuShipInstructIdSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先区分： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreClassS {
            get {
                return ResourceManager.GetString("StoreClassS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷確定処理が正常に終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SUC_UPDATE {
            get {
                return ResourceManager.GetString("SUC_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Transporter {
            get {
                return ResourceManager.GetString("Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterId {
            get {
                return ResourceManager.GetString("TransporterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterName {
            get {
                return ResourceManager.GetString("TransporterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterS {
            get {
                return ResourceManager.GetString("TransporterS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
    }
}
