//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Ship.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrintInvoiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintInvoiceResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Ship.Resources.PrintInvoiceResource", typeof(PrintInvoiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   個口総数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllUnit {
            get {
                return ResourceManager.GetString("AllUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者実績データ連携済みです。発行時のユーザーの拠点情報で再発行します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AltSagawaDoneEdi {
            get {
                return ResourceManager.GetString("AltSagawaDoneEdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発行時のユーザーの拠点情報と違うため、送り状NO・配送業者顧客コードが変更されます。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AltSagawaNotYetEdi {
            get {
                return ResourceManager.GetString("AltSagawaNotYetEdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配達指定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArriveRequestDate {
            get {
                return ResourceManager.GetString("ArriveRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定日配達表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArriveRequestDateDesp {
            get {
                return ResourceManager.GetString("ArriveRequestDateDesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間帯指定コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArriveRequestTime {
            get {
                return ResourceManager.GetString("ArriveRequestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間帯指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArriveRequestTimeName {
            get {
                return ResourceManager.GetString("ArriveRequestTimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   記事 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗出荷分（残{0} / 総{1}）[ITEM納品伝票No：{2} （{3}）] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssortMessage1 {
            get {
                return ResourceManager.GetString("AssortMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗出荷分はすべてスキャンしました [ITEM納品伝票No：{0} （{1}）] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssortMessage2 {
            get {
                return ResourceManager.GetString("AssortMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   　※出荷保留の店舗です。納品書、送り状は発行されません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssortMessage3 {
            get {
                return ResourceManager.GetString("AssortMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バッチ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BatchName {
            get {
                return ResourceManager.GetString("BatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   便種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BinType {
            get {
                return ResourceManager.GetString("BinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNo {
            get {
                return ResourceManager.GetString("BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNoS {
            get {
                return ResourceManager.GetString("BoxNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterIdS {
            get {
                return ResourceManager.GetString("CenterIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷場所 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterName {
            get {
                return ResourceManager.GetString("CenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過去分含む に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChkOldData {
            get {
                return ResourceManager.GetString("ChkOldData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のITEM納品書番号のスキャンを許可する(海外アソートのみ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChkOtherListScan {
            get {
                return ResourceManager.GetString("ChkOtherListScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   代引金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClaimAmount {
            get {
                return ResourceManager.GetString("ClaimAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区分コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClassCd {
            get {
                return ResourceManager.GetString("ClassCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お客様コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientCd {
            get {
                return ResourceManager.GetString("ClientCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorAmount {
            get {
                return ResourceManager.GetString("ColorAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorId {
            get {
                return ResourceManager.GetString("ColorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorName {
            get {
                return ResourceManager.GetString("ColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorResultQty {
            get {
                return ResourceManager.GetString("ColorResultQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ITEM納品伝票番号： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComfirmDialogInvoiceNoS {
            get {
                return ResourceManager.GetString("ComfirmDialogInvoiceNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※即出荷時は本日が出荷伝票日付となります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComfirmDialogMessage1 {
            get {
                return ResourceManager.GetString("ComfirmDialogMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※未来日を指定した場合は出荷保留となり、納品書送り状は発行されません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComfirmDialogMessage2 {
            get {
                return ResourceManager.GetString("ComfirmDialogMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷伝票日付： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComfirmDialogSlipDateS {
            get {
                return ResourceManager.GetString("ComfirmDialogSlipDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷伝票日付を確認してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComfirmDialogTitle {
            get {
                return ResourceManager.GetString("ComfirmDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社住所 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社口座番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyCheckingAccount {
            get {
                return ResourceManager.GetString("CompanyCheckingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社部署名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyDivisionName {
            get {
                return ResourceManager.GetString("CompanyDivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社連絡先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyTelFax {
            get {
                return ResourceManager.GetString("CompanyTelFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   依頼主住所１ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsignorAddress1 {
            get {
                return ResourceManager.GetString("ConsignorAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   依頼主住所２ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsignorAddress2 {
            get {
                return ResourceManager.GetString("ConsignorAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   依頼主住所３ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsignorAddress3 {
            get {
                return ResourceManager.GetString("ConsignorAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   依頼主住所４ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsignorAddress4 {
            get {
                return ResourceManager.GetString("ConsignorAddress4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   依頼主市区町村 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsignorCityName {
            get {
                return ResourceManager.GetString("ConsignorCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷送人Fax に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsignorFax {
            get {
                return ResourceManager.GetString("ConsignorFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご依頼主名1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsignorName {
            get {
                return ResourceManager.GetString("ConsignorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご依頼主名2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsignorName2 {
            get {
                return ResourceManager.GetString("ConsignorName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   依頼主都道府県 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsignorPrefName {
            get {
                return ResourceManager.GetString("ConsignorPrefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご依頼主電話番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsignorTel {
            get {
                return ResourceManager.GetString("ConsignorTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷送人郵便番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsignorZip {
            get {
                return ResourceManager.GetString("ConsignorZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状種類(印刷判定用) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DaibikiFlag {
            get {
                return ResourceManager.GetString("DaibikiFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   集金代行表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DaikoDesp {
            get {
                return ResourceManager.GetString("DaikoDesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliDate {
            get {
                return ResourceManager.GetString("DeliDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お問い合せ送り状NO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliNo {
            get {
                return ResourceManager.GetString("DeliNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状番号2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliNo2 {
            get {
                return ResourceManager.GetString("DeliNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷札送り状バーコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliNoBarcodeNihuda {
            get {
                return ResourceManager.GetString("DeliNoBarcodeNihuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状番号： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliNoS {
            get {
                return ResourceManager.GetString("DeliNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕分コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliShiwakeCd {
            get {
                return ResourceManager.GetString("DeliShiwakeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状使用期限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliUseDate {
            get {
                return ResourceManager.GetString("DeliUseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問合せ先電話番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliVeryCompanyTel {
            get {
                return ResourceManager.GetString("DeliVeryCompanyTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliveryNote {
            get {
                return ResourceManager.GetString("DeliveryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印字制御フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DespFlag {
            get {
                return ResourceManager.GetString("DespFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お届け先住所１ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestAddress1 {
            get {
                return ResourceManager.GetString("DestAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お届け先住所２ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestAddress2 {
            get {
                return ResourceManager.GetString("DestAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お届け先住所３ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestAddress3 {
            get {
                return ResourceManager.GetString("DestAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お届け先住所４ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestAddress4 {
            get {
                return ResourceManager.GetString("DestAddress4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お届け先会社 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestBumon1 {
            get {
                return ResourceManager.GetString("DestBumon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お届け先部署 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestBumon2 {
            get {
                return ResourceManager.GetString("DestBumon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お届け先市区町村 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestCityName {
            get {
                return ResourceManager.GetString("DestCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行先方面名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestDirectName {
            get {
                return ResourceManager.GetString("DestDirectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お届け先名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestName {
            get {
                return ResourceManager.GetString("DestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   届先名称2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestName2 {
            get {
                return ResourceManager.GetString("DestName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   届先名称3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestName3 {
            get {
                return ResourceManager.GetString("DestName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お届け先都道府県 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestPrefName {
            get {
                return ResourceManager.GetString("DestPrefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お届け先電話番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestTel {
            get {
                return ResourceManager.GetString("DestTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お届け先郵便番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestZip {
            get {
                return ResourceManager.GetString("DestZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PC画面で実績入力されています。発行できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrNotDeliNo {
            get {
                return ResourceManager.GetString("ErrNotDeliNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書発行不要の出荷先です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrNotPrnNouhin {
            get {
                return ResourceManager.GetString("ErrNotPrnNouhin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書発行不要の出荷先です。新規発行アクションしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrNotPrnNouhinCom {
            get {
                return ResourceManager.GetString("ErrNotPrnNouhinCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキャンされたケースは全数キャンセル指示されています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorAllCancel {
            get {
                return ResourceManager.GetString("ErrorAllCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヤマト箱サイズが不正です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorBoxSize {
            get {
                return ResourceManager.GetString("ErrorBoxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキャンされたケースにはキャンセル指示が含まれています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorCancel {
            get {
                return ResourceManager.GetString("ErrorCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者顧客コードが未設定です。センター別店舗別配送業者マスタから設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorClientCdSagawa {
            get {
                return ResourceManager.GetString("ErrorClientCdSagawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に入荷実績が登録済みです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorExistsArriveResult {
            get {
                return ResourceManager.GetString("ErrorExistsArriveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検品が必要な出荷先です。検品されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷予定データが紐づいていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorNoArrivePlan {
            get {
                return ResourceManager.GetString("ErrorNoArrivePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当ケースNoもしくは送り状番号は存在しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorNotExist {
            get {
                return ResourceManager.GetString("ErrorNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検品が必要な出荷先です。未検品もしくは検品中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorNotPic {
            get {
                return ResourceManager.GetString("ErrorNotPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗出荷分のケースではありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorNotShipStore {
            get {
                return ResourceManager.GetString("ErrorNotShipStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のITEM納品書番号のケースです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorOtherInvoiceNo {
            get {
                return ResourceManager.GetString("ErrorOtherInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書・送り状はすでに発行されています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorOutPut {
            get {
                return ResourceManager.GetString("ErrorOutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検品不足確認中です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorPicComfirm {
            get {
                return ResourceManager.GetString("ErrorPicComfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状は一度も発行されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorReDeli {
            get {
                return ResourceManager.GetString("ErrorReDeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書は一度も発行されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorReNouhin {
            get {
                return ResourceManager.GetString("ErrorReNouhin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当店舗は棚卸中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorStoreInv {
            get {
                return ResourceManager.GetString("ErrorStoreInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状発行不要の配送業者です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorTransporter {
            get {
                return ResourceManager.GetString("ErrorTransporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名１ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoodsName1 {
            get {
                return ResourceManager.GetString("GoodsName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名２ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoodsName2 {
            get {
                return ResourceManager.GetString("GoodsName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名３ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoodsName3 {
            get {
                return ResourceManager.GetString("GoodsName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名４ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoodsName4 {
            get {
                return ResourceManager.GetString("GoodsName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名５ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoodsName5 {
            get {
                return ResourceManager.GetString("GoodsName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷扱い1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Handling1 {
            get {
                return ResourceManager.GetString("Handling1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷扱い2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Handling2 {
            get {
                return ResourceManager.GetString("Handling2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取扱注意表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HandlingPrecautionsDesp {
            get {
                return ResourceManager.GetString("HandlingPrecautionsDesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保険金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InsuranceAmount {
            get {
                return ResourceManager.GetString("InsuranceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorId {
            get {
                return ResourceManager.GetString("ItemColorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorName {
            get {
                return ResourceManager.GetString("ItemColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemName2 {
            get {
                return ResourceManager.GetString("ItemName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeId {
            get {
                return ResourceManager.GetString("ItemSizeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeIdS {
            get {
                return ResourceManager.GetString("ItemSizeIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeName {
            get {
                return ResourceManager.GetString("ItemSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JAN {
            get {
                return ResourceManager.GetString("JAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KakuDate {
            get {
                return ResourceManager.GetString("KakuDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   担当者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KakuUserName {
            get {
                return ResourceManager.GetString("KakuUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ローカルコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalCd {
            get {
                return ResourceManager.GetString("LocalCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規　　　　　 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上代 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NormalSellingPrice {
            get {
                return ResourceManager.GetString("NormalSellingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品日(日) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NouhinDate {
            get {
                return ResourceManager.GetString("NouhinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品日(月) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NouhinMonth {
            get {
                return ResourceManager.GetString("NouhinMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NouhinNo {
            get {
                return ResourceManager.GetString("NouhinNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   枚数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   着営業所コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OfficeCd {
            get {
                return ResourceManager.GetString("OfficeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オフ率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OffRate {
            get {
                return ResourceManager.GetString("OffRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷姿 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PackingType {
            get {
                return ResourceManager.GetString("PackingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷枚数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PriintCopies {
            get {
                return ResourceManager.GetString("PriintCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発送元センター： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintCenterIdS {
            get {
                return ResourceManager.GetString("PrintCenterIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発送日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintDate {
            get {
                return ResourceManager.GetString("PrintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   続いて送り状を印刷します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintInvoiceMessage {
            get {
                return ResourceManager.GetString("PrintInvoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書、送り状はどちらも発行しない出荷先です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintMassage {
            get {
                return ResourceManager.GetString("PrintMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発行区分： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrnClassS {
            get {
                return ResourceManager.GetString("PrnClassS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お問い合わせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryNo {
            get {
                return ResourceManager.GetString("QueryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状再発行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReDeliPrn {
            get {
                return ResourceManager.GetString("ReDeliPrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RELEASES {
            get {
                return ResourceManager.GetString("RELEASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書再発行　　 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReNouhinPrn {
            get {
                return ResourceManager.GetString("ReNouhinPrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultQty {
            get {
                return ResourceManager.GetString("ResultQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※各配送業者の送り状の出荷元には「発送元センター」の情報が印字されます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SagawaComment {
            get {
                return ResourceManager.GetString("SagawaComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷種別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaleBaseClassName {
            get {
                return ResourceManager.GetString("SaleBaseClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   集荷FAX番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaleOfficeFax {
            get {
                return ResourceManager.GetString("SaleOfficeFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   集荷店名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaleOfficeName {
            get {
                return ResourceManager.GetString("SaleOfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   集荷電話番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaleOfficeTel {
            get {
                return ResourceManager.GetString("SaleOfficeTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   売上区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SalesClassName {
            get {
                return ResourceManager.GetString("SalesClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＜海外アソートスキャン中＞ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScanAssortViewTitle {
            get {
                return ResourceManager.GetString("ScanAssortViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   浪速設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingNaniwa {
            get {
                return ResourceManager.GetString("SettingNaniwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネコポス設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingNekoposu {
            get {
                return ResourceManager.GetString("SettingNekoposu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ecb納品書設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingOkaiage {
            get {
                return ResourceManager.GetString("SettingOkaiage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   楽天納品書設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingRakuten {
            get {
                return ResourceManager.GetString("SettingRakuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   佐川設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingSagawa {
            get {
                return ResourceManager.GetString("SettingSagawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   東納印刷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingTounou {
            get {
                return ResourceManager.GetString("SettingTounou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WaKsnap納品書設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingWaKsnap {
            get {
                return ResourceManager.GetString("SettingWaKsnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヤマト設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingYamato {
            get {
                return ResourceManager.GetString("SettingYamato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipDate {
            get {
                return ResourceManager.GetString("ShipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発店コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipStoreCd {
            get {
                return ResourceManager.GetString("ShipStoreCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先住所１ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToAddress1 {
            get {
                return ResourceManager.GetString("ShipToAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先住所２ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToAddress2 {
            get {
                return ResourceManager.GetString("ShipToAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先住所３ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToAddress3 {
            get {
                return ResourceManager.GetString("ShipToAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先店舗ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreId {
            get {
                return ResourceManager.GetString("ShipToStoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreName {
            get {
                return ResourceManager.GetString("ShipToStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先郵便番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToZip {
            get {
                return ResourceManager.GetString("ShipToZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SizeId {
            get {
                return ResourceManager.GetString("SizeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SizeName {
            get {
                return ResourceManager.GetString("SizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SizeResultQty {
            get {
                return ResourceManager.GetString("SizeResultQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票枚数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipCount {
            get {
                return ResourceManager.GetString("SlipCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票日付は最終月次締め年月以前の日付は指定できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipDateMessage {
            get {
                return ResourceManager.GetString("SlipDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票日付は必須項目です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipDateRequired {
            get {
                return ResourceManager.GetString("SlipDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   決算指定表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecifyDesp {
            get {
                return ResourceManager.GetString("SpecifyDesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＜出荷店舗残一覧＞ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreListTitle {
            get {
                return ResourceManager.GetString("StoreListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値付区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TagClass {
            get {
                return ResourceManager.GetString("TagClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単価 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tanka {
            get {
                return ResourceManager.GetString("Tanka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消費税等 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaxAmount {
            get {
                return ResourceManager.GetString("TaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印字税表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaxAmountDesp {
            get {
                return ResourceManager.GetString("TaxAmountDesp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金額合計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量合計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TotalResultQty {
            get {
                return ResourceManager.GetString("TotalResultQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引形態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransactionForm {
            get {
                return ResourceManager.GetString("TransactionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   個数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   個口バーコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnitBarcode {
            get {
                return ResourceManager.GetString("UnitBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ヤマトの場合はサイズをスキャンしてください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YamatoMsg {
            get {
                return ResourceManager.GetString("YamatoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   60ｻｲｽﾞ:0101、80ｻｲｽﾞ:0102、100ｻｲｽﾞ:0103、120ｻｲｽﾞ:0104、140ｻｲｽﾞ:0105、160ｻｲｽﾞ:0106 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YamatoMsg2 {
            get {
                return ResourceManager.GetString("YamatoMsg2", resourceCulture);
            }
        }
    }
}
