//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Ship.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShpBtoBReference01Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShpBtoBReference01Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Ship.Resources.ShpBtoBReference01Resource", typeof(ShpBtoBReference01Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   バッチNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BatchNo {
            get {
                return ResourceManager.GetString("BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNo {
            get {
                return ResourceManager.GetString("BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブランド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センターコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliNo {
            get {
                return ResourceManager.GetString("DeliNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   明細行数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DetailSum {
            get {
                return ResourceManager.GetString("DetailSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行選択フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsCheck {
            get {
                return ResourceManager.GetString("IsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuSum {
            get {
                return ResourceManager.GetString("ItemSkuSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷確定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KakuDate {
            get {
                return ResourceManager.GetString("KakuDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineNo {
            get {
                return ResourceManager.GetString("LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeDate {
            get {
                return ResourceManager.GetString("MakeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成プログラム名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeProgramName {
            get {
                return ResourceManager.GetString("MakeProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeUserId {
            get {
                return ResourceManager.GetString("MakeUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultQty {
            get {
                return ResourceManager.GetString("ResultQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績数合計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultQtySum {
            get {
                return ResourceManager.GetString("ResultQtySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seq {
            get {
                return ResourceManager.GetString("Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷主ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipperId {
            get {
                return ResourceManager.GetString("ShipperId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷予定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipPlanDate {
            get {
                return ResourceManager.GetString("ShipPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipStatusName {
            get {
                return ResourceManager.GetString("ShipStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先店舗ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreId {
            get {
                return ResourceManager.GetString("ShipToStoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先店舗名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreName {
            get {
                return ResourceManager.GetString("ShipToStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterName {
            get {
                return ResourceManager.GetString("TransporterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateCount {
            get {
                return ResourceManager.GetString("UpdateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新プログラム名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateProgramName {
            get {
                return ResourceManager.GetString("UpdateProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateUserId {
            get {
                return ResourceManager.GetString("UpdateUserId", resourceCulture);
            }
        }
    }
}
