//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Ship.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShpDcAllocationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShpDcAllocationResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Ship.Resources.ShpDcAllocationResource", typeof(ShpDcAllocationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   データ受信日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocDate {
            get {
                return ResourceManager.GetString("AllocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブランドID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrandId {
            get {
                return ResourceManager.GetString("BrandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センターコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   緊急 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmergencyClassName {
            get {
                return ResourceManager.GetString("EmergencyClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指示区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstructClass {
            get {
                return ResourceManager.GetString("InstructClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指示区分名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstructClassName {
            get {
                return ResourceManager.GetString("InstructClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstructQty {
            get {
                return ResourceManager.GetString("InstructQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行選択フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsCheck {
            get {
                return ResourceManager.GetString("IsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorId {
            get {
                return ResourceManager.GetString("ItemColorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorName {
            get {
                return ResourceManager.GetString("ItemColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeId {
            get {
                return ResourceManager.GetString("ItemSizeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeName {
            get {
                return ResourceManager.GetString("ItemSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuId {
            get {
                return ResourceManager.GetString("ItemSkuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineNo {
            get {
                return ResourceManager.GetString("LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オフ率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OffRate {
            get {
                return ResourceManager.GetString("OffRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   売上区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SalesClass {
            get {
                return ResourceManager.GetString("SalesClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   売上区分名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SalesClassName {
            get {
                return ResourceManager.GetString("SalesClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seq {
            get {
                return ResourceManager.GetString("Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷指示ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipInstructId {
            get {
                return ResourceManager.GetString("ShipInstructId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷指示明細ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipInstructSeq {
            get {
                return ResourceManager.GetString("ShipInstructSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷予定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipPlanDate {
            get {
                return ResourceManager.GetString("ShipPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToQty {
            get {
                return ResourceManager.GetString("ShipToQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreClassName {
            get {
                return ResourceManager.GetString("ShipToStoreClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreId {
            get {
                return ResourceManager.GetString("ShipToStoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipToStoreName {
            get {
                return ResourceManager.GetString("ShipToStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterName {
            get {
                return ResourceManager.GetString("TransporterName", resourceCulture);
            }
        }
    }
}
