//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Ship.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransporterChngEcResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransporterChngEcResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Ship.Resources.TransporterChngEcResource", typeof(TransporterChngEcResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   受信日時From に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocDateTimeFrom {
            get {
                return ResourceManager.GetString("AllocDateTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受信日時To に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocDateTimeTo {
            get {
                return ResourceManager.GetString("AllocDateTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引当済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alloced {
            get {
                return ResourceManager.GetString("Alloced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状況 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocStatus {
            get {
                return ResourceManager.GetString("AllocStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引当状況： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllocStatusS {
            get {
                return ResourceManager.GetString("AllocStatusS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送指定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArriveRequestDate {
            get {
                return ResourceManager.GetString("ArriveRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送指定日： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArriveRequestDateS {
            get {
                return ResourceManager.GetString("ArriveRequestDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バッチNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BatchNo {
            get {
                return ResourceManager.GetString("BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNo {
            get {
                return ResourceManager.GetString("BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ケースNo： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNoS {
            get {
                return ResourceManager.GetString("BoxNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者変更・送り状印刷する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnPrint {
            get {
                return ResourceManager.GetString("BtnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者を選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnTransporter {
            get {
                return ResourceManager.GetString("BtnTransporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送エリアを選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnTransporterArea {
            get {
                return ResourceManager.GetString("BtnTransporterArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者変更する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ケースNo： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseNo {
            get {
                return ResourceManager.GetString("CaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterS {
            get {
                return ResourceManager.GetString("CenterS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更後配送業者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangedTransporter {
            get {
                return ResourceManager.GetString("ChangedTransporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更後配送業者： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangedTransporterS {
            get {
                return ResourceManager.GetString("ChangedTransporterS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状番号を採番します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliPrnMsg1 {
            get {
                return ResourceManager.GetString("DeliPrnMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状発行が必要な配送業者の場合、 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliPrnMsg2 {
            get {
                return ResourceManager.GetString("DeliPrnMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状・納品書発行画面より送り状再発行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliPrnMsg3 {
            get {
                return ResourceManager.GetString("DeliPrnMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   郵便番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestZip {
            get {
                return ResourceManager.GetString("DestZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付なし、時間のみ指定は不可。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrNoDate {
            get {
                return ResourceManager.GetString("ErrNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時刻の書式が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrTime {
            get {
                return ResourceManager.GetString("ErrTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受信日時： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeDateS {
            get {
                return ResourceManager.GetString("MakeDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状発行済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Printed {
            get {
                return ResourceManager.GetString("Printed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipInstructId {
            get {
                return ResourceManager.GetString("ShipInstructId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文番号： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipInstructIdS {
            get {
                return ResourceManager.GetString("ShipInstructIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷予定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipPlanDate {
            get {
                return ResourceManager.GetString("ShipPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷予定日： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipPlanDateS {
            get {
                return ResourceManager.GetString("ShipPlanDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シングルの場合、ケースNoは最初に印字した送り状番号となります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SingleMsg {
            get {
                return ResourceManager.GetString("SingleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SizeS {
            get {
                return ResourceManager.GetString("SizeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Transporter {
            get {
                return ResourceManager.GetString("Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送エリア： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterAreaS {
            get {
                return ResourceManager.GetString("TransporterAreaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更後配送業者を指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterIdCom {
            get {
                return ResourceManager.GetString("TransporterIdCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransporterS {
            get {
                return ResourceManager.GetString("TransporterS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未引当 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnAlloc {
            get {
                return ResourceManager.GetString("UnAlloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者を変更します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateMsg {
            get {
                return ResourceManager.GetString("UpdateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送業者変更処理が正常に終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateSuc {
            get {
                return ResourceManager.GetString("UpdateSuc", resourceCulture);
            }
        }
    }
}
