//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wms.Areas.Inventory.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfirmResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfirmResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wms.Areas.Inventory.Resources.ConfirmResource", typeof(ConfirmResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   梱包番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BoxNo {
            get {
                return ResourceManager.GetString("BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷姿区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaseClass {
            get {
                return ResourceManager.GetString("CaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所在区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterClass {
            get {
                return ResourceManager.GetString("CenterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センターコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterId {
            get {
                return ResourceManager.GetString("CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterIdS {
            get {
                return ResourceManager.GetString("CenterIdS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定状況 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmStatus {
            get {
                return ResourceManager.GetString("ConfirmStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸差異リスト発行日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DifferenceListDate {
            get {
                return ResourceManager.GetString("DifferenceListDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸差異リスト発行フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DifferenceListFlag {
            get {
                return ResourceManager.GetString("DifferenceListFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸差異リスト発行ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DifferenceListUserId {
            get {
                return ResourceManager.GetString("DifferenceListUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格付ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GradeId {
            get {
                return ResourceManager.GetString("GradeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InventoryClass {
            get {
                return ResourceManager.GetString("InventoryClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前回仮確定日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InventoryConfirmDate {
            get {
                return ResourceManager.GetString("InventoryConfirmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸確定フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InventoryConfirmFlag {
            get {
                return ResourceManager.GetString("InventoryConfirmFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸確定回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InventoryConfirmSeq {
            get {
                return ResourceManager.GetString("InventoryConfirmSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸開始日： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InventoryDateS {
            get {
                return ResourceManager.GetString("InventoryDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InventoryName {
            get {
                return ResourceManager.GetString("InventoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InventoryNo {
            get {
                return ResourceManager.GetString("InventoryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸No： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InventoryNoS {
            get {
                return ResourceManager.GetString("InventoryNoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸行No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InventorySeq {
            get {
                return ResourceManager.GetString("InventorySeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸開始日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InventoryStartDate {
            get {
                return ResourceManager.GetString("InventoryStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸状況： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InventoryStatusS {
            get {
                return ResourceManager.GetString("InventoryStatusS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行選択フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsCheck {
            get {
                return ResourceManager.GetString("IsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemColorId {
            get {
                return ResourceManager.GetString("ItemColorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品ID(品番) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSizeId {
            get {
                return ResourceManager.GetString("ItemSizeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSkuId {
            get {
                return ResourceManager.GetString("ItemSkuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineNo {
            get {
                return ResourceManager.GetString("LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロケーションコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationCd {
            get {
                return ResourceManager.GetString("LocationCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仮確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProvisionalDecision {
            get {
                return ResourceManager.GetString("ProvisionalDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seq {
            get {
                return ResourceManager.GetString("Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前回ワークID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeqPre {
            get {
                return ResourceManager.GetString("SeqPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外装棚卸許可フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleInventoryFlag {
            get {
                return ResourceManager.GetString("SimpleInventoryFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫有無フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockFlag {
            get {
                return ResourceManager.GetString("StockFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸開始時在庫数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockQtyStart {
            get {
                return ResourceManager.GetString("StockQtyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸本確定を実行しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SUC_CONFORM {
            get {
                return ResourceManager.GetString("SUC_CONFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Undecided {
            get {
                return ResourceManager.GetString("Undecided", resourceCulture);
            }
        }
    }
}
